NHSC/Controllers/OnCallMultidisciplinaryController.cs
using NHSC.Common;
using NHSC.Models.Common;
using NHSC.Models.Entities;
using NHSC.Repository;
using NHSC.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NHSC.Controllers
{
    [CustomErrorHandling]
    //[CheckSessionOut(Values = (int)Menu.Dashboard)]
    public class OnCallMultidisciplinaryController : BaseController
    {

        #region Private Members
        private IUnitOfWork db;
        CommonFunctions objCommon;
        #endregion

        public OnCallMultidisciplinaryController()
        {
            db = new UnitOfWork();
            objCommon = new CommonFunctions();
        }
        public ActionResult Index()
        {
            OnCallMultidisciplinaryModel  objOnCall = new OnCallMultidisciplinaryModel();
            try
            {
                //ViewBag.SiteList = new SelectList(db.Sites.GetSites(), "Value", "Text");
                //ViewBag.DepartmentList = new SelectList(db.Departments.GetDepartments(), "Value", "Text");
                objOnCall.OnCallDates = CommonFunctions.Datetimesetting().ToString(AppConstants.DateShowFormate);
                objOnCall = db.OnCall.GetOnCallMultidisciplinary(objOnCall.OnCallDates, "", "");
                //objOnCall.OnCallDate = CommonFunctions.Datetimesetting();
                //objOnCall.OnCallDates = CommonFunctions.Datetimesetting().ToString(AppConstants.DateShowFormate);
                //objOnCall.OnCallFullDates = CommonFunctions.Datetimesetting().ToString(AppConstants.DateTimeShowFormate);
            }
            catch (Exception)
            {
                throw;
            }
            return View(objOnCall);
        }

        public ActionResult GetForm(string Date = "", string Department = "", string Sites = "")
        {
            OnCallMultidisciplinaryModel objOnCall = new OnCallMultidisciplinaryModel();
            try
            {
                objOnCall = db.OnCall.GetOnCallMultidisciplinary(Date, Department, Sites);
                //objOnCall.OnCallFullDates = CommonFunctions.Datetimesetting().ToString(AppConstants.DateTimeShowFormate);
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_Form", objOnCall);
        }
    }


}

NHSC/Controllers/UserController.cs
using NHSC.Models.Entities;
using NHSC.Models.Common;
using NHSC.Repository;
using NHSC.Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NHSC.Security;
using NHSC.Common;

namespace NHSC.Controllers
{

    [CustomErrorHandling]
    public class UserController : BaseController
    {

        #region Private Members
        private IUnitOfWork db;
        CommonFunctions objCommon;
        #endregion

        public UserController()
        {
            db = new UnitOfWork();
            objCommon = new CommonFunctions();
        }

        #region Crud Opration
        [CheckSessionOut(Values = (int)Menu.User)]
        public ActionResult Index()
        {
            UserModel objUser = new UserModel();
            try
            {
                SetPermision();
            }
            catch (Exception)
            {
                throw;
            }
            return View(objUser);
        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post), ValidateInput(false)]
        [CheckSessionOut(Values = (int)Menu.User)]
        public ActionResult Index(UserModel objUser)
        {
            string strErrorMsg = string.Empty;
            int intStatuscode = 1;
            bool _status = false;
            try
            {
                objUser.ModifyBy = User.UserId;
                objUser.ModifyDate = CommonFunctions.Datetimesetting();
                if (!IsValidData(objUser, ref strErrorMsg))
                {
                    return GetMessage(0, strErrorMsg, objUser.UserId.ToString());
                }
                _status = db.User.InsertData(objUser, ref strErrorMsg);
                if (objUser.UserId == 0)
                {
                    strErrorMsg = Resources.Resource.RecordSaveSuccessfully;
                }
                else
                {
                    strErrorMsg = Resources.Resource.RecordUpdateSuccessfully;
                }
            }
            catch (Exception)
            {
                throw;
            }
            return GetMessage(intStatuscode, strErrorMsg, objUser.UserId.ToString());
        }

        [HttpPost]
        [CheckSessionOut(Values = (int)Menu.User)]
        public ActionResult DeleteRecord(long Id)
        {
            string strErrorMsg = string.Empty;
            int intStatuscode = 1;
            try
            {
                if (!db.Common.IsAssignToAnyModule(AppConstants.User, Id, ref strErrorMsg))
                {
                    bool Status = db.User.DeleteData(Id, User.UserId, CommonFunctions.Datetimesetting());
                    strErrorMsg = Resources.Resource.RecordDeletedSuccessfully;
                }
                else
                {
                    intStatuscode = 0;
                }
             
            }
            catch (Exception)
            {
                throw;
            }
            return GetMessage(intStatuscode, strErrorMsg, Id.ToString());
        }
        #endregion

        #region Get Method
        [CheckSessionOut(Values = (int)Menu.User)]
        public ActionResult GetListJson()
        {
            List<UserModel> objUserList = new List<UserModel>();
            CommonModel objPaging = new CommonModel();
            try
            {
                BindPagingData(objPaging);

                objUserList = db.User.GetList(objPaging);

                return Json(new { draw = objPaging.Page, recordsFiltered = objPaging.TotalCount, recordsTotal = objPaging.TotalCount, data = objUserList });
            }
            catch (Exception)
            {
                throw;
            }
        }
        [CheckSessionOut(Values = (int)Menu.User)]
        public ActionResult GetForm(long Id = 0)
        {
            UserModel objUser = new UserModel();
            try
            {
                ViewBag.GroupList = new SelectList(db.UserGroup.GetUserGroup(), "Value", "Text");
                objUser = db.User.GetDetails(Id);
                if (Id == 0)
                {
                    objUser.Status = 1;
                }
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_Form", objUser);
        }
        [CheckSessionOut(Values = (int)Menu.User)]
        public ActionResult GetView(long Id = 0)
        {
            UserModel objUser = new UserModel();
            try
            {
                ViewBag.GroupList = new SelectList(db.UserGroup.GetUserGroup(), "Value", "Text");
                objUser = db.User.GetDetails(Id);
                if (Id == 0)
                {
                    objUser.Status = 1;
                }
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_View", objUser);
        }
        [CheckSessionOut(Values = (int)Menu.User)]
        public ActionResult GetList()
        {
            UserModel objUserModel = new UserModel();
            try
            {

            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_List", objUserModel);
        }

        #endregion

        #region Asssign department 
        [CheckSessionOut(Values = (int)Menu.User)]
        public ActionResult GetDepartmentAssign(long Id = 0)
        {
            UserModel objUser = new UserModel();
            try
            {
                ViewBag.UserList = new SelectList(db.User.UserDepartmentList(), "Value", "Text");
                objUser.UserId = Id;

            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_AssignDepartment", objUser);
        }
        [CheckSessionOut(Values = (int)Menu.User)]
        public ActionResult GetDepartmentAssignList(long Id = 0)
        {
            List<AssignDepartmentToUserModel> objDepartList = new List<AssignDepartmentToUserModel>();
            CommonModel objPaging = new CommonModel();
            try
            {
                BindPagingForDepartmentData(objPaging);
                objPaging.Id = Id;
                objDepartList = db.Departments.GetDepartmentList(objPaging);
              
                return Json(new { draw = objPaging.Page, recordsFiltered = objPaging.TotalCount, recordsTotal = objPaging.TotalCount, data = objDepartList });
            }
            catch (Exception)
            {
                throw;
            }
        }

        [CheckSessionOut(Values = (int)Menu.User)]
        public ActionResult GetDepartmentAssignById(long Id = 0)
        {
            UserModel objUser = new UserModel();
            string DepartmentIds = "";
            try
            {
                objUser.UserId = Id;
                DepartmentIds = db.Departments.GetDepartmentIds(Id);
                ViewBag.DepartmentIds = DepartmentIds;

            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_AssignDepartmentList", objUser);
        }

        [CheckSessionOut(Values = (int)Menu.User)]
        [HttpPost]
        public ActionResult SaveAssignDepartment(long Id = 0, string DepartmentIds = "")
        {
            UserModel objUser = new UserModel();
            try
            {
                if (!string.IsNullOrEmpty(DepartmentIds) && Id > 0)
                {
                    objUser.ModifyBy = User.UserId;
                    objUser.ModifyDate = CommonFunctions.Datetimesetting();
                    objUser.UserId = Id;
                    db.Departments.AssignDepartmentToUser(objUser, DepartmentIds);
                }
                else
                {
                    return GetMessage(0, "Select atleast one user or department to assign");
                }
                objUser.UserId = Id;
            }
            catch (Exception)
            {
                throw;
            }
            return GetMessage(1, "Successfully assign department to user");
        }
        #endregion

        #region Change Password
        // change forgot password get
        public ActionResult ChangePassword()
        {
            ChangePassword objChangePwd = new ChangePassword();
            try
            {
                if (objCommon.LoginUserDetails == null || objCommon.LoginUserDetails.UserId == 0)
                {
                    return RedirectToAction("Index", "LogIn");
                }
                objChangePwd.UserId = User.UserId;
            }
            catch (Exception)
            {
                throw;
            }
            return View(objChangePwd);
        }
        // change forgot password save
        [HttpPost]
        public ActionResult ChangePassword(ChangePassword objChangePwd)
        {
            string strErrorMsg = string.Empty;
            try
            {
                if (!IsValidDataChangePasword(objChangePwd, ref strErrorMsg))
                {
                    return GetMessage(0, strErrorMsg, "");
                }
                objChangePwd.ModifyDate = CommonFunctions.Datetimesetting();

                db.User.UpdatePassword(objChangePwd);
            }
            catch (Exception)
            {
                throw;
            }
            return GetMessage(1, Resources.Resource.UpdatePasswordSuccessfully, "");
        }
        #endregion


        #region Change Profile
        public ActionResult MyProfile()
        {
            UserModel objUser = new UserModel();
            try
            {
                if (objCommon.LoginUserDetails == null || objCommon.LoginUserDetails.UserId == 0)
                {
                    return RedirectToAction("Index", "LogIn");
                }
                objUser = db.User.GetDetails(User.UserId);
                ViewBag.GroupList = new SelectList(db.UserGroup.GetUserGroup(), "Value", "Text");
            }

NHSC/Views/Shared/PermissionError.cshtml
@model System.Web.Mvc.HandleErrorInfo
@using NHSC.Resources;
@using NHSC.Models.Common;
@{
    ViewBag.Title1 = "Error";
    Layout = null;
}
<html lang="en">
<head>
    <link href="~/assets/css/pages/error/error-5.css" rel="stylesheet" />
    <link href="~/assets/plugins/global/plugins.bundle.css" rel="stylesheet" />
    <link href="~/assets/plugins/custom/prismjs/prismjs.bundle.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/style.bundle.css" rel="stylesheet" />
</head>

<body id="kt_body" class="header-fixed header-mobile-fixed subheader-enabled sidebar-enabled page-loading">
    <!--begin::Main-->
    <div class="d-flex flex-column flex-root">
        <!--begin::Error-->
        <div class="error error-5 d-flex flex-row-fluid bgi-size-cover bgi-position-center" style="background-image: url(@CommonFunctions.BaseURL/assets/media/error/bg5.jpg);">
            <!--begin::Content-->
            <div class="container d-flex flex-row-fluid flex-column justify-content-md-center p-12">
                <h1 class="error-title font-weight-boldest text-info mt-10 mt-md-0 mb-12">Oops</h1>
                <p class="font-weight-boldest display-4">Something went wrong here.</p>
                <p class="font-size-h3">You dont have permission to access this page  <a  style="color: blue; text-decoration: underline !important;" href="@Url.Action("Index","LogIn")">Back To Login</a></p>
            </div>
            <!--end::Content-->
        </div>
        <!--end::Error-->
    </div>
   
</body>
</html>

NHSC/Views/Shared/_Footer.cshtml
<div class="footer py-2 py-lg-0 my-5 d-flex flex-lg-column" id="kt_footer">
    <!--begin::Container-->
    <div class="container-fluid d-flex flex-column flex-md-row align-items-center justify-content-between">
        <!--begin::Copyright-->
        <div class="text-dark order-2 order-md-1">
            <span class="text-muted font-weight-bold mr-2">2021©</span>
            <a href="javascript:void(0)"  class="text-dark-75 text-hover-primary">InfoSoft NI Ltd.</a>
        </div>
        <!--end::Copyright-->
        <!--begin::Nav-->
        <div class="nav nav-dark order-1 order-md-2">
            <a href="https://www.infosoftni.com" target="_blank" class="nav-link pl-3 pr-0">Contact</a>
        </div>
        <!--end::Nav-->
    </div>
    <!--end::Container-->
</div>

NHSC/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <title>@ViewBag.Title</title>

    <link rel="shortcut icon" href="~/assets/media/img/favicon.ico" />
    @Styles.Render("~/Content/maincss")
    @Scripts.Render("~/script/jquerymain")

</head>
<body id="kt_body" class="header-fixed header-mobile-fixed sidebar-enabled page-loading">
    <div class="loading-loder" id="AjaxLoader" style="display:none;z-index: 9999999999; position: fixed;  width:100%; text-align: center; background: rgb(0 0 0 / 50%); height:100%; left:0px; bottom:0px; top:0px; right:0px;  ">
        <div class="strip-holder" style="    background: #fff; width: 100px; margin: 0px auto;  margin-top: 19%;    border-radius: 6px;">
            <img src="~/assets/media/img/loader.gif" style="width: 100px; position: relative;    z-index: 999999;" />
        </div>
    </div>

    <!--begin::Main-->
    <!--begin::Header Mobile-->
    @Html.Partial("_MobileHeader")
    <!--end::Header Mobile-->

    <div class="d-flex flex-column flex-root">
        <!--begin::Page-->
        <div class="d-flex flex-row flex-column-fluid page">
            <!--begin::Aside-->
            @*@Html.Partial("_AsideMenu")*@
            <!--end::Aside-->
            <!--begin::Wrapper-->
            <div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">
                <!--begin::Header-->
                @Html.Partial("_TopMenu")
                <!--end::Header-->
                <!--begin::Content-->
                @RenderBody()
                <!--end::Content-->
                <!--begin::Footer-->
                @Html.Partial("_Footer")
                <!--end::Footer-->

            </div>
            <!--end::Wrapper-->
            <!--begin::Aside Secondary-->
            @Html.Partial("_AsideSecoundry")
            <!--end::Aside Secondary-->

        </div>
        <!--end::Page-->
    </div>
    <!--end::Main-->
    <!--begin::notification popup-->
    @Html.Partial("_NotificationPopUp")
    <!--end::notification popup-->

    <script>var HOST_URL = "https://localhost:44315/";</script>
    <!--begin::Global Config(global config for global JS scripts)-->
    <!--end::Global Config-->


    @Scripts.Render("~/script/jquerybundle")
    @RenderSection("scripts", required: false)

    <script>
             function LoginCheck() {
        $.ajax({
            url: '@Url.Action("CheckLogin", "LogIn")',
            type: "GET",
            success: function (response) {
                if (!response) {
            if (localStorage != undefined) {
                        localStorage.clear();
                    }
                    window.location.href = '@Url.Action("Index", "LogIn")';
                }
            },
            error: function (er) {
            }
        });
    }
    </script>
</body>
</html>

NHSC/Views/Shared/_LogInLayout.cshtml
@using System.Web.Optimization;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    <link rel="shortcut icon" href="~/assets/media/img/favicon.ico" />

    @Styles.Render("~/Content/logincss")
    @Scripts.Render("~/script/jquerymain")
</head>

<body id="kt_body" class="header-fixed header-mobile-fixed subheader-enabled sidebar-enabled page-loading">

    @RenderBody()


    @Scripts.Render("~/script/loginjs")
    @RenderSection("scripts", required: false)
</body>
</html>

NHSC/Views/Shared/_MobileHeader.cshtml
<div id="kt_header_mobile" class="header-mobile header-mobile-fixed">
    <!--begin::Logo-->
    <a href="index.html">
        <img alt="Logo" src="~/assets/media/logos/logo-letter-1.png" class="logo-default max-h-30px" />
    </a>
    <!--end::Logo-->
    <!--begin::Toolbar-->
    <div class="d-flex align-items-center">
        <button class="btn p-0 burger-icon burger-icon-left rounded-0" id="kt_header_mobile_toggle">
            <span></span>
        </button>
        <button class="btn btn-hover-icon-primary p-0 ml-5" id="kt_sidebar_mobile_toggle">
            <span class="svg-icon svg-icon-xl">
                <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Substract.svg-->
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <rect x="0" y="0" width="24" height="24" />
                        <path d="M6,9 L6,15 C6,16.6568542 7.34314575,18 9,18 L15,18 L15,18.8181818 C15,20.2324881 14.2324881,21 12.8181818,21 L5.18181818,21 C3.76751186,21 3,20.2324881 3,18.8181818 L3,11.1818182 C3,9.76751186 3.76751186,9 5.18181818,9 L6,9 Z" fill="#000000" fill-rule="nonzero" />
                        <path d="M10.1818182,4 L17.8181818,4 C19.2324881,4 20,4.76751186 20,6.18181818 L20,13.8181818 C20,15.2324881 19.2324881,16 17.8181818,16 L10.1818182,16 C8.76751186,16 8,15.2324881 8,13.8181818 L8,6.18181818 C8,4.76751186 8.76751186,4 10.1818182,4 Z" fill="#000000" opacity="0.3" />
                    </g>
                </svg>
                <!--end::Svg Icon-->
            </span>
        </button>
        <button class="btn btn-hover-icon-primary p-0 ml-2" id="kt_aside_mobile_toggle">
            <span class="svg-icon svg-icon-xl">
                <!--begin::Svg Icon | path:assets/media/svg/icons/General/User.svg-->
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <polygon points="0 0 24 0 24 24 0 24" />
                        <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" />
                        <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z" fill="#000000" fill-rule="nonzero" />
                    </g>
                </svg>
                <!--end::Svg Icon-->
            </span>
        </button>
    </div>
    <!--end::Toolbar-->
</div>

NHSC/Views/Shared/_TopMenu.cshtml
@using NHSC.Models.Common;
@using NHSC.Common;
@using NHSC.Security;
@{
    CommonFunctions objCommon = new CommonFunctions();
}
@Scripts.Render("~/script/Validation")
<style>
    .font-Poppins {
        font-family: Poppins-Regular !important
    }
</style>
<div id="kt_header" class="header header-fixed">
    <!--begin::Header Wrapper-->
    <div class="header-wrapper rounded-top-xl d-flex flex-grow-1 align-items-center">
        <!--begin::Container-->
        <div class="container-fluid d-flex align-items-center justify-content-end justify-content-lg-between flex-wrap">
            <!--begin::Menu Wrapper-->
            <div class="header-menu-wrapper header-menu-wrapper-left" id="kt_header_menu_wrapper">
                <!--begin::Menu-->
                <div id="kt_header_menu" class="header-menu header-menu-mobile header-menu-layout-default">
                    <!--begin::Nav-->
                    <ul class="menu-nav">
                        @if (objCommon.LoginUserDetails != null && objCommon.LoginUserDetails.MenuList != null && objCommon.LoginUserDetails.MenuList.Count > 0)
                        {
                            foreach (var menu in objCommon.LoginUserDetails.MenuList.Where(x => x.ParentId == 0 && x.View == true && x.IsShowInMenu == true))
                            {
                                if (objCommon.LoginUserDetails.MenuList.Where(x => x.ParentId == menu.MenuId && x.View == true && x.IsShowInMenu == true).Count() > 0)
                                {
                                    <li class="menu-item menu-item-submenu menu-item-rel clsRemoveActive" data-menu-toggle="hover" aria-haspopup="true" id="Menu_@menu.MenuId">
                                        @if (menu.MenuName == "Dashboard")
                                        {
                                            <a href="@Url.Action(menu.Action, menu.Controller)" class="menu-link" onclick="ShowLoader()">
                                                <span class="menu-text menu-text-active">@menu.MenuName</span>
                                                <i class="menu-arrow"></i>
                                            </a>
                                        }
                                        else
                                        {
                                            <a href="javascript:void(0);" class="menu-link menu-toggle">
                                                <span class="menu-text menu-text-active">@menu.MenuName</span>
                                                <span class="menu-desc"></span>
                                                <i class="menu-arrow"></i>
                                            </a>
                                        }
                                        <div class="menu-submenu menu-submenu-classic menu-submenu-left">
                                            <ul class="menu-subnav">
                                                @foreach (var submenu in objCommon.LoginUserDetails.MenuList.Where(x => x.ParentId == menu.MenuId && x.View == true && x.IsShowInMenu == true))
                                                {
                                                    <li class="menu-item clsRemoveSubActive" id="SubMenu_@submenu.MenuId" aria-haspopup="true">
                                                        <a href="@Url.Action(submenu.Action, submenu.Controller)" class="menu-link border-menu" onclick="ShowLoader()">
                                                            <span class="svg-icon menu-icon">
                                                                <i class="fa flaticon2-arrow"></i>
                                                            </span>
                                                            <span class="menu-text menu-subitem-text-active font-Poppins">@submenu.MenuName</span>
                                                        </a>
                                                    </li>
                                                }
                                            </ul>
                                        </div>
                                    </li>
                                }
                                else
                                {
                                    <li class="menu-item menu-item-submenu menu-item-rel clsRemoveActive" data-menu-toggle="hover" aria-haspopup="true" id="Menu_@menu.MenuId">
                                        <a href="@Url.Action(menu.Action, menu.Controller)" class="menu-link" onclick="ShowLoader()">
                                            <span class="menu-text menu-text-active">@menu.MenuName</span>
                                            <i class="menu-arrow"></i>
                                        </a>
                                    </li>
                                }
                            }


                        }
                        else
                        {
                            <li class="menu-item menu-item-submenu menu-item-rel clsRemoveActive" data-menu-toggle="hover" aria-haspopup="true" id="Menu_@Menu.Dashboard">
                                <a href="@Url.Action("Index", "Dashboard")" class="menu-link" onclick="ShowLoader()">
                                    <span class="menu-text menu-text-active">Dashboard</span>
                                    <i class="menu-arrow"></i>
                                </a>
                                <div class="menu-submenu menu-submenu-classic menu-submenu-left">
                                    <ul class="menu-subnav">
                                        <li class="menu-item clsRemoveSubActive" id="SubMenu_@Menu.OnCallMultidisciplinar" aria-haspopup="true">
                                            <a href="@Url.Action("Index", "OnCallMultidisciplinary")" class="menu-link border-menu" onclick="ShowLoader()">
                                                <span class="svg-icon menu-icon">
                                                    <i class="fa flaticon2-arrow"></i>
                                                </span>
                                                <span class="menu-text menu-subitem-text-active font-Poppins">On Call Multidisciplinary</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        }
                    </ul>
                    <!--end::Nav-->
                </div>
                <!--end::Menu-->
            </div>
            <!--end::Menu Wrapper-->
            <!--begin::Toolbar-->
            @if (objCommon.LoginUserDetails != null && objCommon.LoginUserDetails.MenuList != null && objCommon.LoginUserDetails.MenuList.Count > 0)
            {
                <div class="d-flex align-items-center py-3 py-lg-2">
                    <!--begin::Dropdown-->
                    <div class="dropdown mr-2" data-toggle="tooltip" title="" data-placement="left">
                        <a href="#" class="btn btn-icon btn-light h-40px w-40px" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="svg-icon svg-icon-lg svg-icon-info">
                                <!--begin::Svg Icon | path:assets/media/svg/icons/Communication/Clipboard-check.svg-->
                                <i class="fa fa-user"></i>
                                <!--end::Svg Icon-->
                            </span>
                        </a>
                        <div class="dropdown-menu p-0 m-0 dropdown-menu-anim-up dropdown-menu-md dropdown-menu-right">
                            <!--begin::Navigation-->
                            <ul class="navi navi-hover py-5">
                                <li class="navi-item">
                                    <a href="@Url.Action("MyProfile","User")" class="navi-link">
                                        <span class="navi-icon">
                                            <i class="flaticon-user"></i>
                                        </span>
                                        <span class="navi-text">Profile</span>
                                    </a>
                                </li>
                                <li class="navi-item">
                                    <a href="@Url.Action("ChangePassword","User")" class="navi-link">
                                        <span class="navi-icon">
                                            <i class="flaticon-security"></i>
                                        </span>
                                        <span class="navi-text">Change Password</span>
                                    </a>
                                </li>
                                <li class="navi-separator my-3"></li>
                                <li class="navi-item">
                                    <a href="@Url.Action("Logout","LogIn")" class="navi-link" onclick="ShowLoader(),ClearState();">
                                        <span class="navi-icon">
                                            <i class="flaticon-logout"></i>
                                        </span>
                                        <span class="navi-text">Log Out</span>
                                    </a>
                                </li>
                            </ul>
                            <!--end::Navigation-->
                        </div>
                    </div>
                    <!--end::Dropdown-->
                </div>
            }
            <!--end::Toolbar-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Header Wrapper-->
</div>
<script>
    function ClearState() {
        if (localStorage != undefined) {
            localStorage.clear();
        }
    }
</script>