NHSC/Controllers/ActualRotaController.cs
using NHSC.Models.Entities;
using NHSC.Models.Common;
using NHSC.Repository;
using NHSC.Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NHSC.Security;
using NHSC.Common;

namespace NHSC.Controllers
{
    [CheckSessionOut(Values = (int)Menu.ActualRota)]
    [CustomErrorHandling]
    public class ActualRotaController : BaseController
    {

        #region Private Members
        private IUnitOfWork db;
        CommonFunctions objCommon;
        #endregion

        public ActualRotaController()
        {
            db = new UnitOfWork();
            objCommon = new CommonFunctions();
        }

        #region Crud Opration
        public ActionResult Index()
        {
            ActualRotaModel objActualRotaModel = new ActualRotaModel();
            try
            {
                ViewBag.RotaTemplateList = new SelectList(db.RotaTemplate.GetRotaTemplate(""), "RotaTemplateId", "RotaTemplateName");
                SetPermision();
            }
            catch (Exception)
            {
                throw;
            }
            return View(objActualRotaModel);
        }

        #endregion

        #region Get Method


        public ActionResult GetForm(long Id = 0)
        {
            ActualRotaModel objActualRotaModel = new ActualRotaModel();
            try
            {
                if (Id > 0)
                    objActualRotaModel = db.ActualRota.GetActualRotaList(Id,User.UserId);
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_Form", objActualRotaModel);
        }
        public ActionResult GetView(long Id = 0)
        {
            ActualRotaModel objActualRotaModel = new ActualRotaModel();
            try
            {
                objActualRotaModel = db.ActualRota.GetActualRotaList(Id,User.UserId);
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_View", objActualRotaModel);
        }

        public ActionResult LoadStaffPopup(long tempid = 0, long assignid = 0, long staffid = 0)
        {
            StaffPopUp objStaffPopUp = new StaffPopUp();
            try
            {

                ViewBag.StaffList = new SelectList(db.Staff.GetStaff(User.UserId), "Value", "Text");
                objStaffPopUp = db.ActualRota.GetActualRota(assignid);

                ViewBag.Note = "You can select only time between " + objStaffPopUp.ActualStartTime + " To " + (objStaffPopUp.ActualEndTime == "23:59" ? "24:00" : objStaffPopUp.ActualEndTime);
                ViewBag.Note1 = "Atleast " + AppConstants.MinutedifferenceTime + " minute difference required";
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_StaffPopUp", objStaffPopUp);
        }

        public ActionResult LoadStaffPopupMulti(string[] assignid)
        {
            StaffPopUp objStaffPopUp = new StaffPopUp();
            try
            {

                ViewBag.StaffList = new SelectList(db.Staff.GetStaff(User.UserId), "Value", "Text");
                objStaffPopUp = db.ActualRota.GetActualRota(CommonFunctions.ValidlongValue(assignid[0]));
                objStaffPopUp.ActualRotaIds = string.Join(",", assignid);
                ViewBag.Note = "You can select only time between " + objStaffPopUp.ActualStartTime + " To " + (objStaffPopUp.ActualEndTime == "23:59" ? "24:00" : objStaffPopUp.ActualEndTime);
                ViewBag.Note1 = "Atleast " + AppConstants.MinutedifferenceTime + " minute difference required";
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_StaffPopUpMulti", objStaffPopUp);
        }


        public ActionResult ChangeStaff(StaffPopUp objStaffPopUp)
        {
            string strMessage = "";
            try
            {
                if (db.ActualRota.CheckActualMainSatffExits(objStaffPopUp))
                {
                    objStaffPopUp.msg = "Staff already assgin in another shift with same time";
                    objStaffPopUp.statusCode = 0;
                    return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
                }

                if (objStaffPopUp.IsSplit)
                {
                    if (!ValidateData(objStaffPopUp, ref strMessage))
                    {
                        objStaffPopUp.statusCode = 0;
                        objStaffPopUp.msg = strMessage;
                        return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
                    }

                }
                db.ActualRota.AssignNewStaff(objStaffPopUp, User.UserId, CommonFunctions.Datetimesetting());
                objStaffPopUp.statusCode = 1;
                objStaffPopUp.msg = "Successfully updated actual rota";

            }
            catch (Exception)
            {
                throw;
            }
            return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ChangeStaffMulti(StaffPopUp objStaffPopUp)
        {
            string strMessage = "";
            try
            {
                string[] arryids = objStaffPopUp.ActualRotaIds.Split(',');

                foreach (var item in arryids)
                {
                    objStaffPopUp.ActualRotaId = CommonFunctions.ValidlongValue(item);
                    if (db.ActualRota.CheckActualMainSatffExits(objStaffPopUp))
                    {
                        objStaffPopUp.msg = "Staff already assgin in another shift with same time";
                        objStaffPopUp.statusCode = 0;
                        return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
                    }

                    if (objStaffPopUp.IsSplit)
                    {
                        if (!ValidateData(objStaffPopUp, ref strMessage))
                        {
                            objStaffPopUp.statusCode = 0;
                            objStaffPopUp.msg = strMessage;
                            return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
                        }
                    }
                }
                foreach (var item in arryids)
                {
                    objStaffPopUp.ActualRotaId = CommonFunctions.ValidlongValue(item);
                    db.ActualRota.AssignNewStaff(objStaffPopUp, User.UserId, CommonFunctions.Datetimesetting());
                }
                objStaffPopUp.statusCode = 1;
                objStaffPopUp.msg = "Successfully updated actual rota";

            }
            catch (Exception)
            {
                throw;
            }
            return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UnAssignStaff(long assignid = 0)
        {
            StaffPopUp objStaffPopUp = new StaffPopUp();
            try
            {

                objStaffPopUp.ActualRotaId = assignid;
                db.ActualRota.UnAssignStaff(objStaffPopUp, User.UserId, CommonFunctions.Datetimesetting());
                objStaffPopUp.statusCode = 1;
                objStaffPopUp.msg = "Successfully un assign staff";
            }
            catch (Exception)
            {
                throw;
            }
            return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UnAssignStaffMulti(string assignid = "")
        {
            StaffPopUp objStaffPopUp = new StaffPopUp();
            try
            {
                objStaffPopUp.ActualRotaIds = assignid;
                string[] arryids = assignid.Split(',');
                foreach (var item in arryids)
                {
                    objStaffPopUp.ActualRotaId = CommonFunctions.ValidlongValue(item);
                    db.ActualRota.UnAssignStaff(objStaffPopUp, User.UserId, CommonFunctions.Datetimesetting());
                }
                objStaffPopUp.statusCode = 1;
                objStaffPopUp.msg = "Successfully un assign staff";
            }
            catch (Exception)
            {
                throw;
            }
            return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Other Function

        public void SetPermision()
        {
            try
            {
                Session[AppConstants.EditRecord] = User.MenuList.Where(x => x.View == true && x.MenuId == (int)Menu.ActualRota).FirstOrDefault().Edit;
                Session[AppConstants.DeleteRecord] = User.MenuList.Where(x => x.View == true && x.MenuId == (int)Menu.ActualRota).FirstOrDefault().Delete;
                Session[AppConstants.AddRecord] = User.MenuList.Where(x => x.View == true && x.MenuId == (int)Menu.ActualRota).FirstOrDefault().Add;
                Session[AppConstants.IsShowAll] = User.MenuList.Where(x => x.View == true && x.MenuId == (int)Menu.ActualRota).FirstOrDefault().IsShowAll;
            }
            catch (Exception)
            {
                throw;
            }
        }
        private JsonResult GetMessage(int intStatuscode, string strMessage, string pstrID = "")
        {
            dynamic showMessageString = string.Empty;
            try
            {
                showMessageString = new
                {
                    statusCode = intStatuscode,
                    msg = strMessage,
                    id = pstrID,
                    Error = strMessage,
                    message = strMessage,
                };
                return Json(showMessageString, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public bool ValidateData(StaffPopUp objStaffPopUp, ref string strMessage)
        {
            DateTime aStart;
            DateTime aEnd;
            DateTime sStart;

NHSC/Views/ActualRota/_Form.cshtml
@using System.Web.Optimization;
@using NHSC.Resources;
@using NHSC.Common;
@using NHSC.Models.Common;
@model NHSC.Models.Entities.ActualRotaModel
@{
    ViewBag.Title = "Actual Rota";
}

@Styles.Render("~/Content/wizard3")
<div class="card card-custom">
    <div class="card-body p-0">
        <div class="wizard wizard-3" id="kt_wizard_v3" data-wizard-state="step-first" data-wizard-clickable="true">
            <!--begin: Wizard Body-->
            <div class="row justify-content-center py-10 px-8 py-lg-12 px-lg-10">
                <div class="col-xl-12 col-xxl-12">
                    @if (Model.RotaList == null || Model.RotaList.Count == 0)
                    {
                        <h1 style="text-align:center">No Data Found..</h1>
                    }
                    else
                    {
                        <!--begin: Wizard Form-->
                        using (Ajax.BeginForm("Index", "ActualRota", new AjaxOptions { HttpMethod = "POST", LoadingElementId = "AjaxLoader" }, new { @novalidate = "novalidate", @id = "kt_form", @class = "form", @autocomplete = "off" }))
                        {
                            <div class="pb-5" data-wizard-type="step-content" data-wizard-state="current">
                                @if (Model.RotaList != null && Model.RotaList.Count > 0)
                                {
                                    foreach (var roat in Model.RotaList)
                                    {
                                        <div>
                                            <h1>@roat.RotaTemplateName  <input type="button" value="Add Staff To Selected Days" id="btnAddMultiStaff" class="btn btn-primary" /></h1>

                                            <table class="table table-bordered table-hover table-checkable">
                                                <thead>
                                                    <tr>
                                                        <th>Date</th>
                                                        @foreach (var shift in roat.ShiftList.OrderBy(x=>x.OrderSeq))
                                                        {
                                                            <th>
                                                                @shift.ShiftName  <br /> @shift.StartTime<span>-</span>
                                                                @(shift.EndTime== "23:59" ? "24:00" : shift.EndTime)
                                                                <input type="checkbox" class="clsCheckShift" data-id="@shift.ShiftId" />
                                                            </th>
                                                        }
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @{int dayscount = 0;}
                                                    @foreach (var day in roat.DaysList)
                                                    {
                                                        <tr>
                                                            <td>
                                                                @day.RotaDate
                                                                <input type="checkbox" class="clsCheckDate" data-id="@dayscount" />
                                                            </td>
                                                            @foreach (var shifyday in day.DayWiseShiftList.OrderBy(x => x.OrderSeq))
                                                            {
                                                                string Class = dayscount + "_" + shifyday.ShiftId;

                                                                <td style="background-color: @(!string.IsNullOrEmpty(shifyday.HolidayName) ? "#ff91a4" : shifyday.ColorName) ">
                                                                    <a href="javascript:void(0)" class="@(roat.IsAllowEdit?"EditRec" : "") clsRota_@shifyday.ActualRotaId @Class" data-tempid="@shifyday.RotaTemplateId" data-assignid="@shifyday.ActualRotaId" data-staffid="@shifyday.StaffId">
                                                                        @if (shifyday.IsSplit)
                                                                        {
                                                                            <span class="Staff_@shifyday.ActualRotaId">
                                                                                @(string.IsNullOrEmpty(shifyday.StaffName) ? "N/A" : shifyday.StaffName) (@shifyday.StartTime - @(shifyday.EndTime== "23:59" ? "24:00" : shifyday.EndTime))
                                                                                <br />
                                                                                @(string.IsNullOrEmpty(shifyday.SplitStaffName) ? "N/A" : shifyday.SplitStaffName) (@shifyday.SplitStartTime - @(shifyday.SplitEndTime == "23:59" ? "24:00" : shifyday.SplitEndTime))
                                                                            </span>
                                                                        }
                                                                        else
                                                                        {
                                                                            <span class="Staff_@shifyday.ActualRotaId">  @(string.IsNullOrEmpty(shifyday.StaffName) ? "N/A" : shifyday.StaffName) </span>

                                                                        }
                                                                    </a>
                                                                </td>
                                                            }
                                                        </tr>

                                                        dayscount = dayscount + 1;
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    }
                                }
                            </div>
                        }
                        <!--end: Wizard Form-->
                    }
                </div>
            </div>
            <!--end: Wizard Body-->
        </div>
    </div>
</div>

@*@Scripts.Render("~/script/wizard3")*@
<script>
    $(document).ready(function () {


    });
</script>

NHSC/Views/ActualRota/_StaffPopUp.cshtml
@using System.Web.Optimization;
@using NHSC.Resources;
@using NHSC.Common;
@using NHSC.Models.Common;
@model NHSC.Models.Entities.StaffPopUp
@{
    ViewBag.Title = "Staff PopUp";
}
<!--begin::Modal-->
<div class="modal fade" id="divStaffPopup" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Change Staff</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <form class="form" id="frmStaff">
                <div class="modal-body">
                    <div class="form-group row remove_margin">
                        <label class="col-form-label text-right col-lg-3 col-sm-12">Staff</label>
                        <div class="col-lg-9 col-md-9 col-sm-12">
                            <div class="input-group date" id="kt_datetimepicker_9" data-target-input="nearest">
                                @Html.HiddenFor(x => x.ActualRotaId)
                                @Html.HiddenFor(x => x.RotaTemplateId)
                                @Html.HiddenFor(x => x.ActualStartTime)
                                @Html.HiddenFor(x => x.ActualEndTime)
                                @Html.HiddenFor(x => x.StaffName)
                                @Html.HiddenFor(x => x.SplitStaffName)
                                @Html.HiddenFor(x => x.RotaDate)
                                @Html.DropDownListFor(x => x.StaffId, ViewBag.StaffList as SelectList, "--Select--", new { @class = "form-control clsddl reqfield clsStaffId", @style = "width:100%" })
                                <span class="form-text text-muted error_Validation StaffId"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row remove_margin">

                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="row">
                                @{string List = "";}
                                @foreach (var item in Model.StaffList)
                                {
                                    <div class="col-6">
                                        <div class="" style="display: table-row; text-align: center">
                                            <div class="" style="display: table-cell; padding-left: 5px;padding-right: 5px">
                                                <p class="remove_margin_p">
                                                    @item.ColumnName :
                                                </p>
                                            </div>

                                            <div class="" style="display: table-cell; padding-left: 5px;padding-right: 5px">
                                                <p class="remove_margin_p">
                                                    @item.Value
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>

                        </div>
                    </div>
                    <div class="form-group row remove_margin">
                        <label class="col-form-label text-right col-lg-3 col-sm-12">Is Split Shift</label>
                        <div class="col-lg-3 col-md-3 col-sm-3">
                            <div class="input-group date" id="kt_datetimepicker_9" data-target-input="nearest">
                                @Html.CheckBoxFor(x => x.IsSplit, new { @class = "form-control clsddl", @style = "height:30px;margin-right: 50px;" })
                                <span class="form-text text-muted error_Validation IsSplit"></span>
                            </div>
                        </div>
                    </div>
                    <div id="divSplitShift" class="@(Model.IsSplit == true ? "" : "hidden")">
                        <div class="form-group row remove_margin">
                            <label class="col-form-label text-right col-lg-3 col-sm-12">Split Staff</label>
                            <div class="col-lg-9 col-md-9 col-sm-12">
                                <div class="input-group date" id="kt_datetimepicker_9" data-target-input="nearest">
                                    @Html.DropDownListFor(x => x.SplitStaffId, ViewBag.StaffList as SelectList, "--Select--", new { @class = "form-control clsddl clsreqfield clsSplitStaffId " + (Model.IsSplit == true ? "reqfield" : "") + " ", @style = "width:100%" })
                                    <span class="form-text text-muted error_Validation SplitStaffId"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row remove_margin">

                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <div class="row">
                                    @{ List = "";}
                                    @foreach (var item in Model.SplitStaffList)
                                    {
                                        <div class="col-6">
                                            <div class="" style="display: table-row; text-align: center">
                                                <div class="" style="display: table-cell; padding-left: 5px;padding-right: 5px">
                                                    <p class="remove_margin_p">
                                                        @item.ColumnName :
                                                    </p>
                                                </div>

                                                <div class="" style="display: table-cell; padding-left: 5px;padding-right: 5px">
                                                    <p class="remove_margin_p">
                                                        @item.Value
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <!--begin::Input-->
                                <div class="form-group">
                                    <label>Split Start Time <span class="error_Validation">*</span></label>
                                    @Html.TextBoxFor(x => x.SplitStartTime, new { @class = "form-control clstext clsreqfield clsSplitStartTime clsTime " + (Model.IsSplit == true ? "reqfield" : "") + "", @placeholder = "Split Start Time", @value = Model.SplitStartTime })
                                    <span class="form-text text-muted error_Validation SplitStartTime"></span>
                                </div>
                                <!--end::Input-->
                            </div>
                            <div class="col-xl-6">
                                <!--begin::Input-->
                                <div class="form-group">
                                    <label>Split End Time <span class="error_Validation">*</span></label>
                                    @Html.TextBoxFor(x => x.SplitEndTime, new { @class = "form-control clstext clsreqfield clsSplitEndTime clsTime " + (Model.IsSplit == true ? "reqfield" : "") + "", @placeholder = "Split End Time", @value = Model.SplitEndTime })
                                    <span class="form-text text-muted error_Validation SplitEndTime"></span>
                                </div>
                                <!--end::Input-->
                            </div>
                        </div>
                        @*<div class="form-group row">
            <label class="col-form-label text-right col-lg-3 col-sm-12">Set End Time s 24 Hour</label>
            <div class="col-lg-3 col-md-3 col-sm-3">
                <div class="input-group date" id="kt_datetimepicker_9" data-target-input="nearest">
                    @Html.CheckBoxFor(x => x.IsSplit, new { @class = "form-control clsddl", @style = "height:30px;margin-right: 50px;" })
                    <span class="form-text text-muted error_Validation IsSplit"></span>
                </div>
            </div>
        </div>*@
                        <div class="form-group row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <div class="input-group date" id="kt_datetimepicker_9" data-target-input="nearest">
                                    <span class="form-text text-muted error_Validation">
                                        Note:</br>
                                        1. @ViewBag.Note
                                        </br> 2.  @ViewBag.Note1
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-primary mr-2" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-secondary" id="btnUpdateStaff">Update</button>
                    @if (Model.StaffId > 0 || Model.SplitStaffId > 0)
                    {
                        <button type="button" class="btn btn-secondary" id="btnUpdateUnAssign">Un Assign</button>
                    }
                </div>
            </form>
        </div>
    </div>
</div>
<!--end::Modal-->

<script>
    $(document).ready(function () {
        $(".clsStaffId").select2({
            selectOnClose: true
        });
        $(".clsSplitStaffId").select2({
            selectOnClose: true
        });

        var starttime = $('.clsSplitStartTime').timepicker({
            minuteStep: 1,
            showMeridian: false,
            snapToStep: true,
        });
        var endtime = $('.clsSplitEndTime').timepicker({
            minuteStep: 1,
            showMeridian: false,
            snapToStep: true,
        });

        $(".clsSplitEndTime").val('@Model.SplitEndTime');
        $(".clsSplitStartTime").val('@Model.SplitStartTime');

        $(".clsSplitEndTime").focus();
        $(".clsSplitStartTime").focus();

        $('.clsSplitStartTime').timepicker('hideWidget');
        $('.clsSplitEndTime').timepicker('hideWidget');

        $('body').on('click', '.clsTime', function (event) {
            $(this).focus();
        });

        $('body').on('click', '#IsSplit', function (event) {
            if ($(this).is(":checked")) {
                $("#divSplitShift").removeClass("hidden");
                $(".clsreqfield").addClass("reqfield");
            } else {
                $("#divSplitShift").addClass("hidden");
                $(".clsreqfield").removeClass("reqfield");
            }
        });



    });
</script>