NHSC/Controllers/MultidisciplinaryDashboardController.cs
using NHSC.Common;
using NHSC.Models.Common;
using NHSC.Models.Entities;
using NHSC.Repository;
using NHSC.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NHSC.Controllers
{
    [CustomErrorHandling]
    [CheckSessionOut(Values = (int)Menu.MultidisciplinaryDashboard)]
    public class MultidisciplinaryDashboardController : BaseController
    {

        #region Private Members
        private IUnitOfWork db;
        CommonFunctions objCommon;
        #endregion

        public MultidisciplinaryDashboardController()
        {
            db = new UnitOfWork();
            objCommon = new CommonFunctions();
        }
        public ActionResult Index()
        {
            OnCallModel objOnCall = new OnCallModel();
            try
            {
                ViewBag.SiteList = new SelectList(db.Sites.GetSites(), "Value", "Text");
                ViewBag.DepartmentList = new SelectList(db.Departments.GetDepartments(), "Value", "Text");
                objOnCall.OnCallDates = CommonFunctions.Datetimesetting().ToString(AppConstants.DateShowFormate);
                //objOnCall = db.OnCall.GetOnCallActualMultiRotaList(objOnCall.OnCallDates, "", "",0);
                objOnCall.OnCallDate = CommonFunctions.Datetimesetting();
                objOnCall.OnCallDates = CommonFunctions.Datetimesetting().ToString(AppConstants.DateShowFormate);
                objOnCall.OnCallFullDates = CommonFunctions.Datetimesetting().ToString(AppConstants.DateTimeShowFormate);
                ViewBag.MultiList = new SelectList(db.MultidisciplinaryRota.GetMultidisciplinaryRota(), "Value", "Text");
            }
            catch (Exception)
            {
                throw;
            }
            return View(objOnCall);
        }

        public ActionResult GetForm(string Date = "", string Department = "", string Sites = "", int MultiId = 0)
        {
            OnCallModel objOnCall = new OnCallModel();
            try
            {
                if (MultiId > 0)
                {
                    objOnCall = db.OnCall.GetOnCallActualMultiRotaList(Date, Department, Sites, MultiId,User.UserId);
                }
                objOnCall.OnCallFullDates = CommonFunctions.Datetimesetting().ToString(AppConstants.DateTimeShowFormate);
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_Form", objOnCall);
        }
    }


}

NHSC/Views/MultidisciplinaryDashboard/Index.cshtml
@using System.Web.Optimization;
@using NHSC.Resources;
@using NHSC.Common;
@using NHSC.Models.Common;
@model NHSC.Models.Entities.OnCallModel
@{
    ViewBag.Title = "Multidisciplinary Dashboard";
}
@Scripts.Render("~/script/Validation")
<script>

        $(document).ready(function () {
            SetActiveMenu('@Convert.ToInt16(Menu.MultidisciplinaryDashboard)');
            $('body').on('change', '#MultidisciplinaryId', function (event) {
                try {
                    LoadForm();
                } catch (e) {
                    console.log(e);
                }
            });
        });

    $('body').on('click', '.EditRec', function (event) {
        try {
            clearInterval();
        LoadStaffChangePopup($(this).attr("data-tempid"), $(this).attr("data-assignid"), $(this).attr("data-staffid"));
    } catch (e) {
        console.log(e);
    }
    });

    $('body').on('click', '#btnSearch', function (event) {
        try {
            LoadForm();
        } catch (e) {
            console.log(e);
        }
    });

 

    $('body').on('click', '#btnUpdateStaff', function (event) {
        try {

            if (!BindSpclValidationEventClick("#frmStaff")) {
                return false;
            }
            else
            {

                //var assignid = $("#ActualRotaId").val();
                //var staffid = $("#StaffId").val();
                //var templateid = $("#RotaTemplateId").val();
                var staffname = $("#StaffId option:selected").text();
                var splitstaffname = $("#SplitStaffId option:selected").text();
                $("#StaffName").val(staffname);
                $("#SplitStaffName").val(splitstaffname);
                var data = $("#frmStaff").serialize();

              LoginCheck();
                ShowLoader();
                //var dataObject = JSON.stringify({
                //    "assignid": assignid,
                //    "staffid": staffid,
                //});
                var strUrl = '@Url.Action("ChangeStaff", "MultidisciplinaryActualRotaTemplate")';
                $.ajax({
                    url: strUrl,
                    type: 'POST',
                    data: data,
                    success: function (result) {
                        if (result != undefined && result.statusCode == 1) {
                            ShowMessageBox(1, result.msg);
                            //if (result.SplitStaffId > 0) {
                            //    var first = result.StaffName + "(" + result.StartTime + "-" + (result.EndTime == "23:59" ? "24:00" : result.EndTime) + ")"
                            //    var Secound = result.SplitStaffName + "(" + result.SplitStartTime + "-" + (result.SplitEndTime == "23:59" ? "24:00" : result.SplitEndTime) + ")"
                            //    $(".Staff_" + result.ActualRotaId).html(first + " <br/>" + Secound);
                            //} else {
                            //    $(".Staff_" + result.ActualRotaId).html(result.StaffName);
                            //}
                            //$(".clsRota_" + result.ActualRotaId).attr("data-staffid", result.StaffId);
                            $("#divStaffPopup").modal("hide");
                            $("#divPopup").html("");
                            $(".modal-backdrop").remove();
                            SetIntervel();
                            $("#btnSearch").click();
                        }
                        else
                        {
                            ShowMessageBox(0, result.msg);
                        }
                    },
                    complete: function () {
                        HideLoader();
                    },
                    error: function (err) {
                        console.log(err);

                    }
                });
                return false;
            }
        } catch (e) {
            console.log(e);
        }
    });

   function LoadStaffChangePopup(tempid, assignid, staffid) {
        LoginCheck();
        ShowLoader();
        var dataObject = JSON.stringify({
            "tempid": tempid,
            "assignid": assignid,
            "staffid": staffid,
        });
        var strUrl = '@Url.Action("LoadStaffPopup", "MultidisciplinaryActualRotaTemplate")';
        $.ajax({
            url: strUrl,
            type: 'POST',
            data: dataObject,
            async: true,
            contentType: 'application/json',
            success: function (result) {
                $("#divPopup").html(result);
                $("#divStaffPopup").modal();

            },
            complete: function () {
                HideLoader();
            },
            error: function (err) {
                console.log(err);

            }
        });
        return false;
    }

    function LoadForm() {

        var id = $(".clsMulti").val();

        ShowLoader();
        var dataObject = JSON.stringify({
            "Date": $("#OnCallDate").val(),
            "Department": $("#DepartmentIds").val(),
            "Sites": $("#SiteIds").val(),
            "MultiId": $("#MultidisciplinaryId").val(),
        });
        var strUrl = '@Url.Action("GetForm", "MultidisciplinaryDashboard")';
        $.ajax({
            url: strUrl,
            type: 'POST',
            data: dataObject,
            async: true,
            contentType: 'application/json',
            success: function (result) {
                $("#divBodyData").html(result);
            },
            complete: function () {
                HideLoader();
            },
            error: function (err) {
                console.log(err);

            }
        });
        
        return false;
    }
</script>
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6 subheader-transparent" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1" style="width:100%">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5" style="width:100%">
                    <!--begin::Page Title-->
                    <div class="col-md-3">
                        <h5 class="text-dark font-weight-bold my-1 mr-5" style="width:70%" id="headerTitle">
                            Not logged in user
                        </h5>
                    </div>
                    <div class="col-md-6">
                        @Html.DropDownListFor(x => x.MultidisciplinaryId, ViewBag.MultiList as SelectList, "--Select Multidisciplinary Template--", new { @class = "form-control clsddl  clsMulti", @style = "width:500px;" })
                    </div>


                    <div class="col-md-3"><h5 class="text-dark font-weight-bold my-1 mr-5" id="headerTitle">Page Loaded at <span class="clsLoadTime">@Model.OnCallFullDates</span></h5></div>

                    
                    <!--end::Page Title-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <div class="d-flex align-items-center">

            </div>
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <div class="col-xl-12 col-xxl-12">

            <div class="row">
                <div class="col-xl-2">
                    <!--begin::Input-->
                    <div class="form-group">
                        <label>Date <span class="error_Validation">*</span></label>
                        @Html.TextBoxFor(x => x.OnCallDate, "{0:dd-MM-yyyy}", new { @id = "OnCallDate", @readonly = "readonly", @class = "form-control reqfield clsDate", @style = "height:43px", @placeholder = "Date", @type = "text" })
                        @Html.HiddenFor(x => x.OnCallDates)
                        <span class="form-text text-muted error_Validation OnCallDate"></span>
                    </div>
                    <!--end::Input-->
                </div>
                <div class="col-xl-4">
                    <div class="form-group">
                        <label>Department <span class="error_Validation">*</span></label>
                        <select class="form-control select2 clsddl  clsDepartment" id="Departmen" name="Departmen" multiple="multiple" onchange="SelectValueChosen(this, 'DepartmentIds', true)" style="width:100%">
                            @foreach (var item in ViewBag.DepartmentList)
                            {
                                <option value="@item.Value">@item.Text</option>
                            }
                        </select>
                        <span class="form-text text-muted error_Validation ShiftIds"></span>
                        @Html.HiddenFor(x => x.DepartmentIds, new { @class = "form-control clstext" })
                    </div>
                </div>
                <div class="col-xl-4">
                    <div class="form-group">
                        <label>Site</label>
                        <select class="form-control select2 clsddl  clsSite" id="Site" name="Site" multiple="multiple" onchange="SelectValueChosen(this, 'SiteIds', true)" style="width:100%">
                            @foreach (var item in ViewBag.SiteList)
                            {
                                <option value="@item.Value">@item.Text</option>
                            }
                        </select>
                        <span class="form-text text-muted error_Validation SiteIds"></span>
                        @Html.HiddenFor(x => x.SiteIds, new { @class = "form-control clstext" })
                    </div>
                </div>
                <div class="col-xl-2">
                    <!--begin::Input-->
                    <div class="form-group">
                        <label>&nbsp;</label>
                        <button type="button" id="btnSearch" class="btn btn-success font-weight-bolder text-uppercase px-9 py-4" style=" margin-top: 16px;">Search</button>
                    </div>
                    <!--end::Input-->
                </div>
            </div>

            <div class="container-fluid" id="divBodyData">
                @Html.Partial("_Form")
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>
</div>
<div id="divPopup"></div>
<script>
    $(document).ready(function () {
        $(".clsMulti").select2({
            selectOnClose: true
        });
        $(".clsSite").select2({
            placeholder: ('Select Site'),
            selectOnClose: true
        });
        $(".clsDepartment").select2({
            placeholder: ('Select Department'),
            selectOnClose: true
        });

        //$("#OnCallDate").val('@Model.OnCallDates');
        var date = $("#OnCallDate").datepicker({
            minView: 1,
            format: "dd-mm-yy",
            //startDate: new Date,
            defaultViewDate: new Date(),
            autoclose: true,
            todayHighlight: !0,
            pickerPosition: "bottom-left",
        });
        $("#OnCallDate").focus();

        $("#Site").focus();
        date.datepicker("hide");
        clearInterval();


    });

    function SetIntervel() {
        setInterval(function () { $("#btnSearch").click(); }, 60000);
    }
</script>

NHSC/Views/MultidisciplinaryDashboard/_Form.cshtml
@using System.Web.Optimization;
@using NHSC.Resources;
@using NHSC.Common;
@using NHSC.Models.Common;
@model NHSC.Models.Entities.OnCallModel
@{
    ViewBag.Title = "Not logged in user";
    CommonFunctions objCommon = new CommonFunctions();
}
<style>
    p {
        margin: 0;
    }
</style>

@Styles.Render("~/Content/wizard3")
<div class="card card-custom">
    <div class="card-body p-0">
        <div class="wizard wizard-3" id="kt_wizard_v3" data-wizard-state="step-first" data-wizard-clickable="true">
            <!--begin: Wizard Body-->
            <div class="row justify-content-center py-10 px-8 py-lg-12 px-lg-10">
                <div class="col-xl-12 col-xxl-12">
                    @if (Model.RotaList == null || Model.RotaList.Count == 0)
                    {
                        <h1 style="text-align:center">No Data Found..</h1>
                    }
                    else
                    {
                        <!--begin: Wizard Form-->
                        using (Ajax.BeginForm("Index", "MultidisciplinaryActualRotaTemplate", new AjaxOptions { HttpMethod = "POST", LoadingElementId = "AjaxLoader" }, new { @novalidate = "novalidate", @id = "kt_form", @class = "form", @autocomplete = "off" }))
                        {
                            <div class="pb-5" data-wizard-type="step-content" data-wizard-state="current">
                                @if (Model.RotaList != null && Model.RotaList.Count > 0)
                                {
                                    foreach (var roat in Model.RotaList)
                                    {
                                        <div>
                                            <h1>@roat.RotaTemplateName (@roat.RotaDate)</h1>
                                            <table class="table table-bordered table-hover table-checkable">
                                                <thead>
                                                    <tr>
                                                        @foreach (var shift in roat.ShiftList)
                                                        {
                                                            <th>
                                                                @shift.ShiftName  <br /> @shift.StartTime<span>-</span>
                                                                @(shift.EndTime== "23:59" ? "24:00" : shift.EndTime)
                                                            </th>
                                                        }
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var day in roat.DaysList)
                                                    {
                                                        <tr>
                                                            @foreach (var shifyday in day.DayWiseShiftList)
                                                            {

                                                                <td style="background-color: @(!string.IsNullOrEmpty(shifyday.HolidayName) ? "#ff91a4" : shifyday.ColorName) ">
                                                                    <a href="javascript:void(0)" class="@(objCommon.LoginUserDetails==null?"": (@roat.IsAllowEdit ? "EditRec" : "")) clsRota_@shifyday.ActualRotaId" data-tempid="@shifyday.RotaTemplateId" data-assignid="@shifyday.ActualRotaId" data-staffid="@shifyday.StaffId">
                                                                        @if (shifyday.IsSplit)
                                                                        {
                                                                            <span class="Staff_@shifyday.ActualRotaId">
                                                                                (@shifyday.StartTime - @(shifyday.EndTime== "23:59" ? "24:00" : shifyday.EndTime))
                                                                                @if (shifyday.StaffId > 0)
                                                                                {
                                                                                    foreach (var staff in shifyday.StaffList)
                                                                                    {
                                                                                        if (!string.IsNullOrEmpty(staff.Value))
                                                                                        {
                                                                                            <p> @staff.ColumnName :  @staff.Value</p>
                                                                                        }
                                                                                    }
                                                                                }
                                                                                else
                                                                                {
                                                                                    <p>N/A</p>
                                                                                }
                                                                            </span>
                                                                            <span class="Staff_@shifyday.ActualRotaId">
                                                                                (@shifyday.SplitStartTime - @(shifyday.SplitEndTime == "23:59" ? "24:00" : shifyday.SplitEndTime))
                                                                                @if (shifyday.StaffId > 0)
                                                                                {
                                                                                    foreach (var staff in shifyday.SplitStaffList)
                                                                                    {
                                                                                        if (!string.IsNullOrEmpty(staff.Value))
                                                                                        {
                                                                                            <p> @staff.ColumnName :  @staff.Value</p>
                                                                                        }
                                                                                    }
                                                                                }
                                                                                else
                                                                                {
                                                                                    <p>N/A</p>
                                                                                }
                                                                            </span>
                                                                        }
                                                                        else
                                                                        {
                                                                            <span class="Staff_@shifyday.ActualRotaId">
                                                                                @if (shifyday.StaffId > 0)
                                                                                {
                                                                                    foreach (var staff in shifyday.StaffList)
                                                                                    {

                                                                                        if (!string.IsNullOrEmpty(staff.Value))
                                                                                        {
                                                                                            <p> @staff.ColumnName :  @staff.Value</p>
                                                                                        }
                                                                                    }
                                                                                }
                                                                                else
                                                                                {
                                                                                    <p>N/A</p>
                                                                                }
                                                                            </span>

                                                                        }
                                                                    </a>
                                                                </td>
                                                            }
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    }
                                }
                            </div>
                        }
                        <!--end: Wizard Form-->
                    }
                </div>
            </div>
            <!--end: Wizard Body-->
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

        $(".clsLoadTime").html('@Model.OnCallFullDates');
        clearInterval();
        SetIntervel();
    });
</script>