NHSC/Controllers/MultidisciplinaryActualRotaTemplateController.cs
using NHSC.Models.Entities;
using NHSC.Models.Common;
using NHSC.Repository;
using NHSC.Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NHSC.Security;
using NHSC.Common;

namespace NHSC.Controllers
{
    [CheckSessionOut(Values = (int)Menu.MultidisciplinaryActualRotaTemplate)]
    [CustomErrorHandling]
    public class MultidisciplinaryActualRotaTemplateController : BaseController
    {

        #region Private Members
        private IUnitOfWork db;
        CommonFunctions objCommon;
        #endregion

        public MultidisciplinaryActualRotaTemplateController()
        {
            db = new UnitOfWork();
            objCommon = new CommonFunctions();
        }

        #region Crud Opration
        public ActionResult Index()
        {
            ActualRotaModel objActualRotaModel = new ActualRotaModel();
            try
            {
                ViewBag.MultiList = new SelectList(db.MultidisciplinaryRota.GetMultidisciplinaryRota(), "Value", "Text");
                SetPermision();
            }
            catch (Exception)
            {
                throw;
            }
            return View(objActualRotaModel);
        }

        #endregion

        #region Get Method


        public ActionResult GetForm(long Id = 0)
        {
            ActualRotaModel objActualRotaModel = new ActualRotaModel();
            try
            {
                if (Id > 0)
                    objActualRotaModel = db.ActualRota.GetAssignActualRotaList(Id,User.UserId);
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_Form", objActualRotaModel);
        }
        public ActionResult GetView(long Id = 0)
        {
            ActualRotaModel objActualRotaModel = new ActualRotaModel();
            try
            {
                objActualRotaModel = db.ActualRota.GetAssignActualRotaList(Id,User.UserId);
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_View", objActualRotaModel);
        }

        public ActionResult LoadStaffPopup(long tempid = 0, long assignid = 0, long staffid = 0)
        {
            StaffPopUp objStaffPopUp = new StaffPopUp();
            try
            {

                ViewBag.StaffList = new SelectList(db.Staff.GetStaff(User.UserId), "Value", "Text");
                objStaffPopUp = db.ActualRota.GetActualRota(assignid);

                ViewBag.Note = "You can select only time between " + objStaffPopUp.ActualStartTime + " To " + (objStaffPopUp.ActualEndTime == "23:59" ? "24:00" : objStaffPopUp.ActualEndTime);
                ViewBag.Note1 = "Atleast " + AppConstants.MinutedifferenceTime + " minute difference required";
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_StaffPopUp", objStaffPopUp);
        }

        public ActionResult ChangeStaff(StaffPopUp objStaffPopUp)
        {
            string strMessage = "";
            try
            {
                if (db.ActualRota.CheckActualMainSatffExits(objStaffPopUp))
                {
                    objStaffPopUp.msg = "Staff already assgin in another shift with same time";
                    objStaffPopUp.statusCode = 0;
                    return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
                }

                if (objStaffPopUp.IsSplit)
                {
                    if (!ValidateData(objStaffPopUp, ref strMessage))
                    {
                        objStaffPopUp.statusCode = 0;
                        objStaffPopUp.msg = strMessage;
                        return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
                    }

                }
                db.ActualRota.AssignNewStaff(objStaffPopUp, User.UserId, CommonFunctions.Datetimesetting());
                objStaffPopUp.statusCode = 1;
                objStaffPopUp.msg = "Successfully updated actual rota";

            }
            catch (Exception)
            {
                throw;
            }
            return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UnAssignStaff(long assignid = 0)
        {
            string strMessage = "";
            StaffPopUp objStaffPopUp = new StaffPopUp();
            try
            {
                objStaffPopUp.ActualRotaId = assignid;
                db.ActualRota.UnAssignStaff(objStaffPopUp, User.UserId, CommonFunctions.Datetimesetting());
                objStaffPopUp.statusCode = 1;
                objStaffPopUp.msg = "Successfully un assign staff";
            }
            catch (Exception)
            {
                throw;
            }
            return Json(objStaffPopUp, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Other Function

        public void SetPermision()
        {
            try
            {
                Session[AppConstants.EditRecord] = User.MenuList.Where(x => x.View == true && x.MenuId == (int)Menu.MultidisciplinaryActualRotaTemplate).FirstOrDefault().Edit;
                Session[AppConstants.DeleteRecord] = User.MenuList.Where(x => x.View == true && x.MenuId == (int)Menu.MultidisciplinaryActualRotaTemplate).FirstOrDefault().Delete;
                Session[AppConstants.AddRecord] = User.MenuList.Where(x => x.View == true && x.MenuId == (int)Menu.MultidisciplinaryActualRotaTemplate).FirstOrDefault().Add;
                Session[AppConstants.IsShowAll] = User.MenuList.Where(x => x.View == true && x.MenuId == (int)Menu.MultidisciplinaryActualRotaTemplate).FirstOrDefault().IsShowAll;
            }
            catch (Exception)
            {
                throw;
            }
        }
        private JsonResult GetMessage(int intStatuscode, string strMessage, string pstrID = "")
        {
            dynamic showMessageString = string.Empty;
            try
            {
                showMessageString = new
                {
                    statusCode = intStatuscode,
                    msg = strMessage,
                    id = pstrID,
                    Error = strMessage,
                    message = strMessage,
                };
                return Json(showMessageString, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public bool ValidateData(StaffPopUp objStaffPopUp, ref string strMessage)
        {
            DateTime aStart;
            DateTime aEnd;
            DateTime sStart;
            DateTime sEnd;
            try
            {
                aStart = Convert.ToDateTime("01-01-0001 " + objStaffPopUp.ActualStartTime);
                aEnd = Convert.ToDateTime("01-01-0001 " + objStaffPopUp.ActualEndTime);
                sStart = Convert.ToDateTime("01-01-0001 " + objStaffPopUp.SplitStartTime);
                sEnd = Convert.ToDateTime("01-01-0001 " + objStaffPopUp.SplitEndTime);

                if (objStaffPopUp.SplitStaffId == 0)
                {
                    strMessage = "Please select split staff id";
                    return false;
                }
                else if (objStaffPopUp.SplitStaffId == objStaffPopUp.StaffId)
                {
                    strMessage = "Staff and Split staff can not be same";
                    return false;
                }
                else if (string.IsNullOrEmpty(objStaffPopUp.SplitStartTime))
                {
                    strMessage = "Please select split start time";
                    return false;
                }
                else if (string.IsNullOrEmpty(objStaffPopUp.SplitEndTime))
                {
                    strMessage = "Please select split end time";
                    return false;
                }
                //else if (objStaffPopUp.SplitStartTime != objStaffPopUp.ActualStartTime && objStaffPopUp.SplitEndTime != objStaffPopUp.ActualEndTime)
                //{
                //    strMessage = "Start or end time atleast one time should be match in split start time or split end time";
                //    return false;
                //}
                else if (objStaffPopUp.SplitStartTime == objStaffPopUp.ActualStartTime)
                {
                    //if (sEnd < sStart.AddMinutes(AppConstants.MinutedifferenceTime))
                    //{
                    //    strMessage = "Atleast " + AppConstants.MinutedifferenceTime + " difference required in split time";
                    //    return false;
                    //}
                    //else if (aEnd.AddMinutes(-AppConstants.MinutedifferenceTime) < sEnd)
                    //{
                    //    strMessage = "Atleast " + AppConstants.MinutedifferenceTime + " difference required in split time";
                    //    return false;
                    //}

                    objStaffPopUp.StartTime = objStaffPopUp.SplitEndTime;
                    objStaffPopUp.EndTime = objStaffPopUp.ActualEndTime;
                }
                else if (objStaffPopUp.SplitEndTime == objStaffPopUp.ActualEndTime)
                {
                    //if (sStart > sEnd.AddMinutes(-AppConstants.MinutedifferenceTime))
                    //{
                    //    strMessage = "Atleast " + AppConstants.MinutedifferenceTime + " difference required in split time";
                    //    return false;
                    //}
                    //else if (aStart.AddMinutes(AppConstants.MinutedifferenceTime) > sStart)
                    //{
                    //    strMessage = "Atleast " + AppConstants.MinutedifferenceTime + " difference required in split time";
                    //    return false;
                    //}
                    objStaffPopUp.StartTime = objStaffPopUp.ActualStartTime;

NHSC/Views/MultidisciplinaryActualRotaTemplate/Index.cshtml
@using System.Web.Optimization;
@using NHSC.Resources;
@using NHSC.Common;
@using NHSC.Models.Common;
@model NHSC.Models.Entities.ActualRotaModel
@{
    ViewBag.Title = "Multidisciplinary Actual Rota Template";
}
@Scripts.Render("~/script/Validation")
    <script>
        $(document).ready(function () {
            SetActiveMenu('@Convert.ToInt16(Menu.Rota)');
            SetSubActiveMenu('@Convert.ToInt16(Menu.MultidisciplinaryActualRotaTemplate)');

            $('body').on('change', '.clsMulti', function (event) {
                try {
                    LoadForm($(this).val());
                } catch (e) {
                    console.log(e);
                }
            });
        });

    $('body').on('click', '.EditRec', function (event) {
    try {
        LoadStaffChangePopup($(this).attr("data-tempid"), $(this).attr("data-assignid"), $(this).attr("data-staffid"));
    } catch (e) {
        console.log(e);
    }
    });

    $('body').on('click', '.ViewRec', function (event) {
        try {
            LoadView($(this).attr("data-id"));
        } catch (e) {
            console.log(e);
        }
    });


    $('body').on('click', '#btnUpdateStaff', function (event) {
        try {

            if (!BindSpclValidationEventClick("#frmStaff")) {
                return false;
            }
            else
            {

                //var assignid = $("#ActualRotaId").val();
                //var staffid = $("#StaffId").val();
                //var templateid = $("#RotaTemplateId").val();
                var staffname = $("#StaffId option:selected").text();
                var splitstaffname = $("#SplitStaffId option:selected").text();
                $("#StaffName").val(staffname);
                $("#SplitStaffName").val(splitstaffname);
                var data = $("#frmStaff").serialize();

              LoginCheck();
                ShowLoader();
                //var dataObject = JSON.stringify({
                //    "assignid": assignid,
                //    "staffid": staffid,
                //});
                var strUrl = '@Url.Action("ChangeStaff", "MultidisciplinaryActualRotaTemplate")';
                $.ajax({
                    url: strUrl,
                    type: 'POST',
                    data: data,
                    success: function (result) {
                        if (result != undefined && result.statusCode == 1) {
                            ShowMessageBox(1, result.msg);
                            if (result.SplitStaffId > 0) {
                                var first = result.StaffName + "(" + result.StartTime + "-" + (result.EndTime == "23:59" ? "24:00" : result.EndTime) + ")"
                                var Secound = result.SplitStaffName + "(" + result.SplitStartTime + "-" + (result.SplitEndTime == "23:59" ? "24:00" : result.SplitEndTime) + ")"
                                $(".Staff_" + result.ActualRotaId).html(first + " <br/>" + Secound);
                            } else {
                                $(".Staff_" + result.ActualRotaId).html(result.StaffName);
                            }
                            $(".clsRota_" + result.ActualRotaId).attr("data-staffid", result.StaffId);
                            $("#divStaffPopup").modal("hide");
                            $("#divPopup").html("");
                            $(".modal-backdrop").remove();
                        }
                        else
                        {
                            ShowMessageBox(0, result.msg);
                        }
                    },
                    complete: function () {
                        HideLoader();
                    },
                    error: function (err) {
                        console.log(err);

                    }
                });
                return false;
            }
        } catch (e) {
            console.log(e);
        }
    });

        $('body').on('click', '#btnUpdateUnAssign', function (event) {
            try {
              LoginCheck();
                ShowLoader();
                var dataObject = JSON.stringify({
                    "assignid": $("#ActualRotaId").val()
                });
                var strUrl = '@Url.Action("UnAssignStaff", "MultidisciplinaryActualRotaTemplate")';
                $.ajax({
                    url: strUrl,
                    type: 'POST',
                    data: dataObject,
                    async: true,
                    contentType: 'application/json',
                    success: function (result) {
                        if (result != undefined && result.statusCode == 1) {
                            ShowMessageBox(1, result.msg);
                            $(".Staff_" + result.ActualRotaId).html("N/A");
                            $(".clsRota_" + result.ActualRotaId).attr("data-staffid", 0);
                            $("#divStaffPopup").modal("hide");
                            $("#divPopup").html("");
                            $(".modal-backdrop").remove();
                        }
                        else
                        {
                            ShowMessageBox(0, result.msg);
                        }
                    },
                    complete: function () {
                        HideLoader();
                    },
                    error: function (err) {
                        console.log(err);

                    }
                });
                return false;
        } catch (e) {
            console.log(e);
        }
    });


        function LoadStaffChangePopup(tempid, assignid, staffid) {
        LoginCheck();
        ShowLoader();
        var dataObject = JSON.stringify({
            "tempid": tempid,
            "assignid": assignid,
            "staffid": staffid,
        });
        var strUrl = '@Url.Action("LoadStaffPopup", "MultidisciplinaryActualRotaTemplate")';
        $.ajax({
            url: strUrl,
            type: 'POST',
            data: dataObject,
            async: true,
            contentType: 'application/json',
            success: function (result) {
                $("#divPopup").html(result);
                $("#divStaffPopup").modal();
            },
            complete: function () {
                HideLoader();
            },
            error: function (err) {
                console.log(err);

            }
        });
        return false;
    }


    function LoadForm(Id) {
        LoginCheck();
        ShowLoader();
        var dataObject = JSON.stringify({
            "Id": Id,
        });
        var strUrl = '@Url.Action("GetForm", "MultidisciplinaryActualRotaTemplate")';
        $.ajax({
            url: strUrl,
            type: 'POST',
            data: dataObject,
            async: true,
            contentType: 'application/json',
            success: function (result) {
                $("#divBodyData").html(result);
            },
            complete: function () {
                HideLoader();
            },
            error: function (err) {
                console.log(err);

            }
        });
        return false;
    }

    function LoadView(Id) {
        LoginCheck();
        ShowLoader();
        var dataObject = JSON.stringify({
            "Id": Id,
        });
        var strUrl = '@Url.Action("GetView", "MultidisciplinaryActualRotaTemplate")';
        $.ajax({
            url: strUrl,
            type: 'POST',
            data: dataObject,
            async: true,
            contentType: 'application/json',
            success: function (result) {
                $("#divBodyData").html(result);
            },
            complete: function () {
                HideLoader();
            },
            error: function (err) {
                console.log(err);

            }
        });
        return false;
    }

    </script>
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6 subheader-transparent" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5" id="headerTitle">Multidisciplinary Actual Rota Assign</h5>
                    <!--end::Page Title-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <div class="d-flex align-items-center">
                @Html.DropDownListFor(x => x.MultidisciplinaryId, ViewBag.MultiList as SelectList, "--Select Multidisciplinary Template--", new { @class = "form-control clsddl  clsMulti", @style = "width:500px;" })
            </div>
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container-fluid" id="divBodyData">
            @*@Html.Partial("_Form")*@
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
</div>
<div id="divPopup"></div>
@*@Scripts.Render("~/script/wizard3")*@
<script>

    $(document).ready(function () {
        //$(".clsMulti").focus();
        $(".clsMulti").select2({
            selectOnClose: true
        });
    });
</script>

NHSC/Views/MultidisciplinaryActualRotaTemplate/_Form.cshtml
@using System.Web.Optimization;
@using NHSC.Resources;
@using NHSC.Common;
@using NHSC.Models.Common;
@model NHSC.Models.Entities.ActualRotaModel
@{
    ViewBag.Title = "Multidisciplinary Actual Rota Template";
}

@Styles.Render("~/Content/wizard3")
<div class="card card-custom">
    <div class="card-body p-0">
        <div class="wizard wizard-3" id="kt_wizard_v3" data-wizard-state="step-first" data-wizard-clickable="true">
            <!--begin: Wizard Body-->
            <div class="row justify-content-center py-10 px-8 py-lg-12 px-lg-10">
                <div class="col-xl-12 col-xxl-12">
                    @if (Model.RotaList == null || Model.RotaList.Count == 0)
                    {
                        <h1 style="text-align:center">No Data Found..</h1>
                    }
                    else
                    {
                        <!--begin: Wizard Form-->
                        using (Ajax.BeginForm("Index", "MultidisciplinaryActualRotaTemplate", new AjaxOptions { HttpMethod = "POST", LoadingElementId = "AjaxLoader" }, new { @novalidate = "novalidate", @id = "kt_form", @class = "form", @autocomplete = "off" }))
                        {
                            <div class="pb-5" data-wizard-type="step-content" data-wizard-state="current">
                                @if (Model.RotaList != null && Model.RotaList.Count > 0)
                                {
                                    foreach (var roat in Model.RotaList)
                                    {
                                        <div>
                                            <h1>@roat.RotaTemplateName</h1>
                                            <table class="table table-bordered table-hover table-checkable">
                                                <thead>
                                                    <tr>
                                                        <th>Date</th>
                                                        @foreach (var shift in roat.ShiftList)
                                                        {
                                                            <th>
                                                                @shift.ShiftName  <br /> @shift.StartTime<span>-</span>
                                                                @(shift.EndTime== "23:59" ? "24:00" : shift.EndTime)
                                                            </th>
                                                        }
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var day in roat.DaysList)
                                                    {
                                                        <tr>
                                                            <td>@day.RotaDate</td>
                                                            @foreach (var shifyday in day.DayWiseShiftList)
                                                            {

                                                                <td style="background-color: @(!string.IsNullOrEmpty(shifyday.HolidayName) ? "#ff91a4" : shifyday.ColorName) ">
                                                                    <a href="javascript:void(0)" class="@(roat.IsAllowEdit?"EditRec" : "") clsRota_@shifyday.ActualRotaId" data-tempid="@shifyday.RotaTemplateId" data-assignid="@shifyday.ActualRotaId" data-staffid="@shifyday.StaffId">
                                                                        @if (shifyday.IsSplit)
                                                                        {
                                                                        <span class="Staff_@shifyday.ActualRotaId">
                                                                            @(string.IsNullOrEmpty(shifyday.StaffName) ? "N/A" : shifyday.StaffName) (@shifyday.StartTime - @(shifyday.EndTime== "23:59" ? "24:00" : shifyday.EndTime))
                                                                            <br />
                                                                            @(string.IsNullOrEmpty(shifyday.SplitStaffName) ? "N/A" : shifyday.SplitStaffName)(@shifyday.SplitStartTime - @(shifyday.SplitEndTime == "23:59" ? "24:00" : shifyday.SplitEndTime))
                                                                        </span>
                                                                        }
                                                                        else
                                                                        {
                                                                            <span class="Staff_@shifyday.ActualRotaId">  @(string.IsNullOrEmpty(shifyday.StaffName) ? "N/A" : shifyday.StaffName) </span>

                                                                        }
                                                                    </a>
                                                                </td>
                                                            }
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    }
                                }
                            </div>
                        }
                        <!--end: Wizard Form-->
                    }
                </div>
            </div>
            <!--end: Wizard Body-->
        </div>
    </div>
</div>

@*@Scripts.Render("~/script/wizard3")*@
<script>
    $(document).ready(function () {


    });
</script>